:concurrency: 5

:queues:
  - default

:redis:
  url: redis://localhost:6379/1

:scheduler:
  :schedule:
    verify_recurring_orders:
      cron: "0 * * * *" # Every night at midnight
      class: VerifyRecurringOrdersJob
